export { default as CheckIcon } from './CheckIcon.vue'
export { default as CheckIconForm } from './CheckIconForm.vue'
export { default as CrossIcon } from './CrossIcon.vue'
export { default as MinusIcon } from './MinusIcon.vue'
export { default as PlusIcon } from './PlusIcon.vue'
export { default as TelegramIcon } from './social/TelegramIcon.vue'
export { default as VkIcon } from './social/VkIcon.vue'
export { default as YoutubeIcon } from './social/YoutubeIcon.vue'
